import { jsPDF } from "jspdf";
import type { ReportData, ReportPeriod } from "@/types/reports";
import { DAILY_RATE } from "@/services/reports/getAttendanceOverview";
import { PERIOD_LABELS, TEACHER_SALARY } from "@/services/reports/getReportData";

/* ------------------------------------------------------------------ */
/* Helpers                                                             */
/* ------------------------------------------------------------------ */

function schoolClassification(rate: number): string {
  if (rate <= 5) return "Low";
  if (rate <= 10) return "Modest";
  if (rate <= 20) return "Significant";
  if (rate <= 30) return "High";
  return "Extreme";
}

function districtBand(rate: number): string {
  if (rate < 5) return "Satisfactory";
  if (rate < 10) return "Moderate";
  if (rate < 20) return "High";
  return "Extreme";
}

function fmtCurrency(n: number): string {
  return "$" + n.toLocaleString("en-US", { maximumFractionDigits: 0 });
}

function fmtPct(n: number): string {
  return n.toFixed(1) + "%";
}

/* ------------------------------------------------------------------ */
/* PDF Colors                                                          */
/* ------------------------------------------------------------------ */

const C = {
  navy: [30, 41, 59] as [number, number, number],
  body: [71, 85, 105] as [number, number, number],
  light: [148, 163, 184] as [number, number, number],
  emerald: [5, 150, 105] as [number, number, number],
  red: [220, 38, 38] as [number, number, number],
  amber: [217, 119, 6] as [number, number, number],
  orange: [234, 88, 12] as [number, number, number],
  darkRed: [153, 27, 27] as [number, number, number],
  white: [255, 255, 255] as [number, number, number],
  grayBg: [248, 250, 252] as [number, number, number],
  grayBorder: [226, 232, 240] as [number, number, number],
  headerBg: [241, 245, 249] as [number, number, number],
};

/* ------------------------------------------------------------------ */
/* PDF Builder                                                         */
/* ------------------------------------------------------------------ */

export interface PdfConfig {
  districtName: string;
  period: ReportPeriod;
  preparedBy: string;
  date: string;
}

export function buildDistrictReportPdf(data: ReportData, config: PdfConfig): Blob {
  const doc = new jsPDF({ orientation: "portrait", unit: "pt", format: "letter" });
  const W = 612;
  const H = 792;
  const ML = 48;
  const MR = 48;
  const MT = 48;
  const CW = W - ML - MR;

  let y = MT;

  const setColor = (c: [number, number, number]) => { doc.setTextColor(c[0], c[1], c[2]); };
  const setFill = (c: [number, number, number]) => { doc.setFillColor(c[0], c[1], c[2]); };
  const setDraw = (c: [number, number, number]) => { doc.setDrawColor(c[0], c[1], c[2]); };

  function addFooter(pageNum: number) {
    const fy = H - 30;
    doc.setFontSize(7);
    setColor(C.light);
    doc.setFont("helvetica", "normal");
    doc.text("Confidential - Student Data", ML, fy);
    doc.text(`Page ${pageNum} of 2`, W / 2, fy, { align: "center" });
    doc.text(`Generated ${config.date} by Edvera`, W - MR, fy, { align: "right" });
  }

  // ============================================================
  // PAGE 1
  // ============================================================

  // Header
  doc.setFontSize(20);
  doc.setFont("helvetica", "bold");
  setColor(C.navy);
  doc.text("District Attendance Report", ML, y);
  y += 20;

  doc.setFontSize(12);
  doc.setFont("helvetica", "normal");
  setColor(C.body);
  doc.text(config.districtName, ML, y);

  doc.setFontSize(9);
  setColor(C.light);
  doc.text(`${PERIOD_LABELS[config.period]}  |  ${config.date}`, W - MR, y - 8, { align: "right" });
  y += 10;

  setDraw(C.emerald);
  doc.setLineWidth(2);
  doc.line(ML, y, W - MR, y);
  y += 14;

  doc.setFontSize(7.5);
  setColor(C.light);
  doc.text(`Prepared by: ${config.preparedBy}`, ML, y);
  doc.text("Generated by Edvera", W - MR, y, { align: "right" });
  y += 24;

  // --- Section 1: Executive Summary ---
  doc.setFontSize(13);
  doc.setFont("helvetica", "bold");
  setColor(C.navy);
  doc.text("Executive Summary", ML, y);
  y += 16;

  const boxW = (CW - 12) / 2;
  const boxH = 62;
  const boxes = [
    {
      label: "Total Students Enrolled",
      value: data.totalStudents.toLocaleString(),
      context: `Across ${data.schools.length} school${data.schools.length !== 1 ? "s" : ""}`,
      valueColor: C.navy,
    },
    {
      label: "Chronic Absence Rate",
      value: fmtPct(data.chronicRate),
      context: `Classification: ${districtBand(data.chronicRate)}`,
      valueColor: data.chronicRate > 20 ? C.red : data.chronicRate > 10 ? C.amber : C.emerald,
    },
    {
      label: "Projected ADA Revenue Loss",
      value: fmtCurrency(data.projectedLoss),
      context: `At ${fmtCurrency(DAILY_RATE)}/day per-pupil rate`,
      valueColor: C.red,
    },
    {
      label: "Students Requiring Intervention",
      value: data.studentsRequiringIntervention.toLocaleString(),
      context: `${data.elevatedCount} elevated, ${data.softeningCount} softening`,
      valueColor: data.studentsRequiringIntervention > 0 ? C.amber : C.emerald,
    },
  ];

  for (let i = 0; i < 4; i++) {
    const col = i % 2;
    const row = Math.floor(i / 2);
    const bx = ML + col * (boxW + 12);
    const by = y + row * (boxH + 8);
    const box = boxes[i];

    setFill(C.grayBg);
    setDraw(C.grayBorder);
    doc.setLineWidth(0.5);
    doc.roundedRect(bx, by, boxW, boxH, 4, 4, "FD");

    doc.setFontSize(7.5);
    doc.setFont("helvetica", "normal");
    setColor(C.light);
    doc.text(box.label, bx + 10, by + 14);

    doc.setFontSize(18);
    doc.setFont("helvetica", "bold");
    setColor(box.valueColor);
    doc.text(box.value, bx + 10, by + 35);

    doc.setFontSize(7);
    doc.setFont("helvetica", "normal");
    setColor(C.body);
    doc.text(box.context, bx + 10, by + 50);
  }

  y += 2 * (boxH + 8) + 20;

  // --- Section 2: School Breakdown Table ---
  doc.setFontSize(13);
  doc.setFont("helvetica", "bold");
  setColor(C.navy);
  doc.text("School Breakdown", ML, y);
  y += 14;

  const cols = [
    { label: "School", x: ML, w: 150, align: "left" as const },
    { label: "Students", x: ML + 155, w: 55, align: "right" as const },
    { label: "Chronic", x: ML + 215, w: 50, align: "right" as const },
    { label: "Rate", x: ML + 270, w: 50, align: "right" as const },
    { label: "Classification", x: ML + 325, w: 85, align: "left" as const },
    { label: "Projected Loss", x: ML + 415, w: CW - 415 + ML, align: "right" as const },
  ];

  const rowH = 18;
  setFill(C.headerBg);
  doc.rect(ML, y, CW, rowH, "F");
  setDraw(C.grayBorder);
  doc.setLineWidth(0.5);
  doc.line(ML, y + rowH, ML + CW, y + rowH);

  doc.setFontSize(7);
  doc.setFont("helvetica", "bold");
  setColor(C.body);
  for (const col of cols) {
    if (col.align === "right") {
      doc.text(col.label, col.x + col.w - 4, y + 12, { align: "right" });
    } else {
      doc.text(col.label, col.x + 4, y + 12);
    }
  }
  y += rowH;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(7.5);

  const sortedSchools = [...data.schools].sort((a, b) => b.chronicRate - a.chronicRate);

  for (let i = 0; i < sortedSchools.length; i++) {
    const s = sortedSchools[i];
    if (i % 2 === 1) {
      setFill(C.grayBg);
      doc.rect(ML, y, CW, rowH, "F");
    }
    setDraw(C.grayBorder);
    doc.line(ML, y + rowH, ML + CW, y + rowH);

    setColor(C.navy);
    doc.text(s.name.length > 28 ? s.name.slice(0, 26) + "..." : s.name, cols[0].x + 4, y + 12);

    setColor(C.body);
    doc.text(s.students.toLocaleString(), cols[1].x + cols[1].w - 4, y + 12, { align: "right" });
    doc.text(s.chronicCount.toLocaleString(), cols[2].x + cols[2].w - 4, y + 12, { align: "right" });

    const rateColor = s.chronicRate > 20 ? C.red : s.chronicRate > 10 ? C.amber : C.body;
    setColor(rateColor);
    doc.text(fmtPct(s.chronicRate), cols[3].x + cols[3].w - 4, y + 12, { align: "right" });

    setColor(C.body);
    doc.text(schoolClassification(s.chronicRate), cols[4].x + 4, y + 12);

    setColor(C.red);
    doc.text(fmtCurrency(s.projectedLoss), cols[5].x + cols[5].w - 4, y + 12, { align: "right" });

    y += rowH;
  }

  // Total row
  setFill(C.headerBg);
  doc.rect(ML, y, CW, rowH, "F");
  doc.setFont("helvetica", "bold");
  doc.setFontSize(7.5);
  setColor(C.navy);
  doc.text("Total", cols[0].x + 4, y + 12);
  doc.text(data.totalStudents.toLocaleString(), cols[1].x + cols[1].w - 4, y + 12, { align: "right" });

  const totalChronic = data.schools.reduce((s, r) => s + r.chronicCount, 0);
  doc.text(totalChronic.toLocaleString(), cols[2].x + cols[2].w - 4, y + 12, { align: "right" });
  doc.text(fmtPct(data.chronicRate), cols[3].x + cols[3].w - 4, y + 12, { align: "right" });
  doc.text("-", cols[4].x + 4, y + 12);
  setColor(C.red);
  doc.text(fmtCurrency(data.projectedLoss), cols[5].x + cols[5].w - 4, y + 12, { align: "right" });
  y += rowH + 20;

  // --- Section 3: Compliance Summary ---
  doc.setFontSize(13);
  doc.setFont("helvetica", "bold");
  setColor(C.navy);
  doc.text("Compliance Summary", ML, y);
  y += 16;

  setFill(C.grayBg);
  setDraw(C.grayBorder);
  doc.setLineWidth(0.5);
  doc.roundedRect(ML, y, CW, 50, 4, 4, "FD");

  doc.setFontSize(8);
  doc.setFont("helvetica", "normal");
  setColor(C.body);
  doc.text(`Open cases by tier:    Tier 1 (Notification): ${data.tier1Count}    |    Tier 2 (Conference): ${data.tier2Count}    |    Tier 3 (SARB): ${data.tier3Count}`, ML + 12, y + 16);

  doc.text(`Actions completed this period: ${data.actionsCompletedCount}`, ML + 12, y + 32);
  const overdueColor = data.actionsOverdueCount > 0 ? C.red : C.body;
  setColor(overdueColor);
  doc.text(`Actions overdue: ${data.actionsOverdueCount}`, ML + 280, y + 32);

  addFooter(1);

  // ============================================================
  // PAGE 2
  // ============================================================
  doc.addPage();
  y = MT;

  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  setColor(C.light);
  doc.text(`${config.districtName} - District Attendance Report`, ML, y);
  doc.text(config.date, W - MR, y, { align: "right" });
  y += 6;
  setDraw(C.grayBorder);
  doc.setLineWidth(0.5);
  doc.line(ML, y, W - MR, y);
  y += 20;

  // --- Section 4: Attendance Band Distribution ---
  doc.setFontSize(13);
  doc.setFont("helvetica", "bold");
  setColor(C.navy);
  doc.text("Attendance Band Distribution", ML, y);
  y += 18;

  const bands = [
    { label: "Satisfactory (95%+)", count: data.bandSatisfactory, color: C.emerald },
    { label: "At-Risk (90-95%)", count: data.bandAtRisk, color: C.amber },
    { label: "Moderate (80-90%)", count: data.bandModerate, color: C.orange },
    { label: "Severe (70-80%)", count: data.bandSevere, color: C.red },
    { label: "Acute (below 70%)", count: data.bandAcute, color: C.darkRed },
  ];
  const totalForBands = data.totalStudents || 1;

  const barH = 24;
  let barX = ML;
  for (const band of bands) {
    const bw = Math.max((band.count / totalForBands) * CW, 0);
    if (bw > 0) {
      setFill(band.color);
      doc.rect(barX, y, bw, barH, "F");
      if (bw > 30) {
        doc.setFontSize(7);
        doc.setFont("helvetica", "bold");
        setColor(C.white);
        doc.text(`${Math.round((band.count / totalForBands) * 100)}%`, barX + bw / 2, y + barH / 2 + 2.5, { align: "center" });
      }
      barX += bw;
    }
  }
  y += barH + 12;

  for (const band of bands) {
    const pct = ((band.count / totalForBands) * 100).toFixed(1);
    setFill(band.color);
    doc.rect(ML, y, 8, 8, "F");
    doc.setFontSize(8);
    doc.setFont("helvetica", "normal");
    setColor(C.navy);
    doc.text(`${band.label}: ${band.count.toLocaleString()} students (${pct}%)`, ML + 14, y + 7);
    y += 14;
  }
  y += 16;

  // --- Section 5: Recovery Opportunity ---
  doc.setFontSize(13);
  doc.setFont("helvetica", "bold");
  setColor(C.navy);
  doc.text("Recovery Opportunity", ML, y);
  y += 16;

  const chronicStudents = data.schools.reduce((s, r) => s + r.chronicCount, 0);
  const recoveryAmount = Math.round(data.projectedLoss * 0.7);
  const teacherEquiv = Math.floor(recoveryAmount / TEACHER_SALARY);

  setFill([236, 253, 245]);
  setDraw(C.emerald);
  doc.setLineWidth(1);
  doc.roundedRect(ML, y, CW, 58, 4, 4, "FD");

  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  setColor(C.navy);

  const recLine1 = `If ${chronicStudents.toLocaleString()} chronically absent students were recovered to 95% attendance,`;
  const recLine2 = `the district would recover an estimated ${fmtCurrency(recoveryAmount)} in ADA funding --`;
  const recLine3 = `equivalent to ${teacherEquiv} teacher salaries at ${fmtCurrency(TEACHER_SALARY)}/year.`;

  doc.text(recLine1, ML + 14, y + 18);
  doc.setFont("helvetica", "bold");
  setColor(C.emerald);
  doc.text(recLine2, ML + 14, y + 32);
  doc.setFont("helvetica", "normal");
  setColor(C.navy);
  doc.text(recLine3, ML + 14, y + 46);

  y += 78;

  // --- Section 6: Key Risk Indicators ---
  doc.setFontSize(13);
  doc.setFont("helvetica", "bold");
  setColor(C.navy);
  doc.text("Key Risk Indicators", ML, y);
  y += 16;

  const indicators = [
    { label: "Students with elevated risk signals", value: data.elevatedCount, warn: data.elevatedCount > 0 },
    { label: "Students with 20%+ absence rate (severe/acute)", value: data.severeOrAcuteCount, warn: data.severeOrAcuteCount > 0 },
    { label: "Unexcused absence rate district-wide", value: fmtPct(data.unexcusedRate), warn: data.unexcusedRate > 10 },
    { label: "Open compliance cases (all tiers)", value: data.tier1Count + data.tier2Count + data.tier3Count, warn: true },
  ];

  for (const ind of indicators) {
    const val = typeof ind.value === "number" ? ind.value.toLocaleString() : ind.value;
    doc.setFontSize(8);
    doc.setFont("helvetica", "normal");
    setColor(C.body);
    doc.text("•", ML + 4, y);
    doc.text(`${ind.label}:`, ML + 14, y);
    doc.setFont("helvetica", "bold");
    setColor(ind.warn ? C.red : C.navy);
    doc.text(val, ML + 14 + doc.getTextWidth(`${ind.label}: `), y);
    y += 14;
  }

  y += 20;

  // --- Section 7: Methodology Note ---
  setDraw(C.grayBorder);
  doc.setLineWidth(0.5);
  doc.line(ML, y, W - MR, y);
  y += 12;

  doc.setFontSize(6.5);
  doc.setFont("helvetica", "normal");
  setColor(C.light);

  const methLines = [
    `Chronic absence is defined as missing 10% or more of enrolled school days (CA Education Code Sec. 60901(c)(1)). Attendance bands follow`,
    `the Attendance Works classification system. ADA loss is projected using a per-pupil daily rate of ${fmtCurrency(DAILY_RATE)}. Risk signals are computed`,
    `from 30-day attendance trajectories. This report was generated by Edvera (edvera.co).`,
  ];
  for (const line of methLines) {
    doc.text(line, ML, y);
    y += 9;
  }

  addFooter(2);

  return doc.output("blob");
}
